from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "sed -i '' -e 's/^version = \".*\"/version = \"{{version}}\"/' pyproject.toml"
]
post_bump_hooks = [
  "argc publish"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file "$1"
"""

[commit_types]
chore = { changelog_title = "", omit_from_changelog = true }
docs = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
